#! /usr/bin/python
import code
import readline

ic = code.InteractiveConsole()
ic.push("import ds_debug")
ic.push("thread = ds_debug.ReaderThread()")
ic.push("thread.start()")
ic.push("v = thread.values")
ic.push("h = thread.hist")
ic.interact()
